---
common:
  disable_legacy_facts: true

spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
# strict_level: ":error"

Rakefile:
  github_user: mleiner

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
spec/default_facts.yml:
    extra_facts:
        'os':
          'family': 'Debian'
        'networking':
          'domain': 'localnet'
