---
common:
  disable_legacy_facts: true

spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
  #  strict_level: ":error"

Rakefile:
  github_user: mleiner

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
spec/default_facts.yml:
    extra_facts:
        'os':
          'family': 'Debian'
        'networking':
          'domain': 'localnet'
